-- Creación de tablas chimbas

CREATE SEQUENCE HOTELES_SEQUENCE;

-- Tabla hoteles

CREATE TABLE H_HOTELES (ID NUMBER, NOMBRE VARCHAR2 (255 BYTE) NOT NULL, UBICACION VARCHAR2 (255 BYTE) NOT NULL, CATEGORIA VARCHAR2 (255 BYTE) NOT NULL, TELEFONO NUMBER NOT NULL, CONSTRAINT H_HOTELES_PK PRIMARY KEY (ID));

ALTER TABLE H_HOTELES ADD CONSTRAINT CK_HOTEL_CATEGORIA CHECK (CATEGORIA IN ('Cinco estrellas', 'Cuatro estrellas', 'Tres estrellas', 'Dos estrellas', 'Una estrella')) ENABLE;

-- Tabla acompañantes

CREATE TABLE H_ACOMPANANTES (ID_CLIENTE NUMBER, ID_ACOMP NUMBER NOT NULL, NOM_ACOMP VARCHAR2 (255 BYTE) NOT NULL, CONSTRAINT H_ACOMPANANTES_PK PRIMARY KEY  (ID_CLIENTE));

ALTER TABLE H_ACOMPANANTES ADD CONSTRAINT UN_NOM_ACOMP UNIQUE (NOM_ACOMP) ENABLE;

-- Tabla planes

CREATE TABLE H_PLANES (ID NUMBER, NOMBRE VARCHAR2 (255 BYTE) NOT NULL, DESCUENTO NUMBER, NUMNOCHES NUMBER NOT NULL, CONSTRAINT H_PLANES_PK PRIMARY KEY (ID));

ALTER TABLE H_PLANES ADD CONSTRAINT CK_NUMNOCHES CHECK (NUMNOCHES >= 1) ENABLE;

-- Tabla piscinas

CREATE TABLE H_PISCINAS (ID NUMBER, NOMBRE VARCHAR2 (255 BYTE) NOT NULL, PRECIO NUMBER NOT NULL, PAGO_ADICIONAL NUMBER NOT NULL, CAPACIDAD NUMBER NOT NULL, HORARIO_INICIAL VARCHAR2 (255 BYTE) NOT NULL, HORARIO_FINAL VARCHAR2 (255 BYTE) NOT NULL, CONSTRAINT H_PISCINAS_PK PRIMARY KEY (ID));

ALTER TABLE H_PISCINAS ADD CONSTRAINT CK_PISCINA_PRECIO CHECK (PRECIO >= 0) ENABLE;

ALTER TABLE H_PISCINAS ADD CONSTRAINT CK_PISCINA_PAGO_EXTRA CHECK (PAGO_ADICIONAL >= 0) ENABLE;

ALTER TABLE H_PISCINAS ADD CONSTRAINT CK_PISCINA_CAPACIDAD CHECK (CAPACIDAD > 0) ENABLE;

-- Tabla restaurantes bar

CREATE TABLE H_RESTAURANTES_BAR (ID NUMBER, TIPO VARCHAR2 (255 BYTE), NOMBRE VARCHAR2 (255 BYTE) NOT NULL, CAPACIDAD NUMBER NOT NULL, TEMATICA VARCHAR2 (255 BYTE), CONSTRAINT H_RESTAURANTES_BAR_PK PRIMARY KEY (ID));

ALTER TABLE H_RESTAURANTES_BAR ADD CONSTRAINT CK_TIPO_RESBAR CHECK(TIPO IN ('Restaurante', 'Bar'));

-- Tabla spas

CREATE TABLE H_SPAS (ID NUMBER, NOMBRE VARCHAR2 (255 BYTE) NOT NULL, PRECIO NUMBER NOT NULL, PAGO_ADICIONAL NUMBER NOT NULL, CONSTRAINT H_SPAS_PK PRIMARY KEY (ID));

ALTER TABLE H_PISCINAS ADD CONSTRAINT CK_SPA_PRECIO CHECK (PRECIO >= 0) ENABLE;

ALTER TABLE H_PISCINAS ADD CONSTRAINT CK_SPA_PAGO_EXTRA CHECK (PAGO_ADICIONAL >= 0) ENABLE;

-- Tabla supermercados tiendas

CREATE TABLE H_SUPERMERCADOS_TIENDAS (ID NUMBER, NOMBRE VARCHAR2 (255 BYTE) NOT NULL, CONSTRAINT H_SUPERMERCADOS_TIENDAS_PK PRIMARY KEY (ID));

-- Tabla internet

CREATE TABLE H_INTERNET (ID NUMBER, CAPACIDAD NUMBER NOT NULL, PRECIO NUMBER NOT NULL, CONSTRAINT H_INTERNET_PK PRIMARY KEY (ID));

-- Tabla productos instalaciones

CREATE TABLE H_PRODUCTOS_INSTALACIONES (ID_ITEM NUMBER, NOMBRE VARCHAR2 (255 BYTE), PRECIO NUMBER NOT NULL, CONSTRAINT H_PRODUCTOS_INSTALACIONES_PK PRIMARY KEY (ID_ITEM));

-- Tabla prestamo utensilios

CREATE TABLE H_PRESTAMO (ID NUMBER, ID_ITEM NUMBER, TIEMPO NUMBER, PRECIO NUMBER, CONSTRAINT H_PRESTAMO_PK PRIMARY KEY (ID));

ALTER TABLE H_PRESTAMO ADD CONSTRAINT FK_P_ITEM FOREIGN KEY (ID_ITEM) REFERENCES H_PRODUCTOS_INSTALACIONES (ID_ITEM);

-- Tabla salon reunion conferencia

CREATE TABLE H_SALONPRESTAMO (ID NUMBER, TIPO VARCHAR2 (255 BYTE), ID_HOTEL NUMBER, CAPACIDAD NUMBER, COSTO NUMBER, CONSTRAINT H_SALONSALA_PK PRIMARY KEY (ID));

ALTER TABLE H_SALONPRESTAMO ADD CONSTRAINT CK_TIPO_SALON CHECK (TIPO IN ('Salon reunion', 'Salon conferencia'));

-- Tabla lavanderia

CREATE TABLE H_LAVANDERIA (ID NUMBER, TIPO VARCHAR2 (255 BYTE), PRECIOPRENDA NUMBER, CONSTRAINT H_LAVANDERIA_PK PRIMARY KEY (ID));

ALTER TABLE H_LAVANDERIA ADD CONSTRAINT CK_TIPO CHECK(TIPO IN ('Lavado', 'Planchado', 'Embolada'));

-- Tabla gimnasios

CREATE TABLE H_GIMNASIOS (ID NUMBER, NOMBRE VARCHAR2 (255 BYTE) NOT NULL, CAPACIDAD NUMBER, PRECIO NUMBER NOT NULL, PRECIOADICIONAL NUMBER NOT NULL, CONSTRAINT H_GIMNASIOS_PK PRIMARY KEY (ID));

-- Tabla tienenMaquinas

CREATE TABLE H_TIENENMAQUINAS (ID_GIMNASIO NUMBER, NOMBRE_MAQUINA VARCHAR2 (255) NOT NULL, CONSTRAINT H_TIENENMAQUINAS_PK PRIMARY KEY (ID_GIMNASIO));

ALTER TABLE H_TIENENMAQUINAS ADD CONSTRAINT FK_TM_GIMNASIOS FOREIGN KEY (ID_GIMNASIO) REFERENCES H_GIMNASIOS (ID) ENABLE;

-- Tabla servicios hotel

CREATE TABLE H_SERVICIOS_HOTEL (ID NUMBER, IDHOTEL NUMBER, ID_SPA NUMBER, ID_SUPERMERCADOTIENDA NUMBER, ID_PISCINA NUMBER, ID_RESTAURANTEBAR NUMBER, ID_GIMNASIO NUMBER, ID_PRESTAMO NUMBER, ID_PRESTAMOSALON NUMBER, ID_INTERNET NUMBER, ID_LAV_PLAN_EMB NUMBER, CONSTRAINT H_SERVICIOS_HOTEL_PK PRIMARY KEY (ID));
	
ALTER TABLE H_SERVICIOS_HOTEL ADD CONSTRAINT FK_S_HOTEL FOREIGN KEY (IDHOTEL) REFERENCES H_HOTELES (ID) ENABLE;

-- Tabla reservaciones hotel

CREATE TABLE H_RESERVACIONES_HOTEL (ID NUMBER, ID_USUARIO NUMBER, FECHALLEGADA VARCHAR2 (255 BYTE) NOT NULL, FECHAPARTIDA VARCHAR2 (255 BYTE) NOT NULL, NUMEROPERSONAS NUMBER NOT NULL, PLANPAGO NUMBER, ID_SERVICIO NUMBER, ID_HABITACION NUMBER, TERMINADA NUMBER, CONSTRAINT H_RESERVACIONES_HOTEL_PK PRIMARY KEY (ID));

ALTER TABLE H_RESERVACIONES_HOTEL CK_TERMINADA CHECK(TERMINADA IN(0,1));

-- Tabla cuentas

CREATE TABLE H_CUENTAS (ID NUMBER, CUENTA NUMBER NOT NULL, NUM_SERVICIOS NUMBER NOT NULL, CONSTRAINT H_CUENTAS_PK PRIMARY KEY (ID));

-- Tabla roles

CREATE TABLE H_ROLES (ID NUMBER, NOMBRE_ROL VARCHAR2 (255 BYTE) NOT NULL, DESCRIPCION VARCHAR2 (255 BYTE) NOT NULL, CONSTRAINT H_ROLES_PK PRIMARY KEY (ID));

ALTER TABLE H_ROLES ADD CONSTRAINT CK_ROL CHECK (NOMBRE_ROL IN ('Cliente', 'Recepcionista', 'Empleado', 'Administrador', 'Gerente', 'OrganizadorEventos')) ENABLE;

ALTER TABLE H_ROLES ADD CONSTRAINT ND_NOMBRE_ROL UNIQUE (NOMBRE_ROL);

-- Tabla usuarios

CREATE TABLE H_USUARIOS (TIPODOCUMENTO VARCHAR2 (255 BYTE), NUMDOCUMENTO NUMBER, NOMBRE VARCHAR2 (255 BYTE) NOT NULL, CORREO VARCHAR2 (255 BYTE), TELEFONO NUMBER NOT NULL, ROL NUMBER, CONSTRAINT H_USUARIOS_PK PRIMARY KEY (NUMDOCUMENTO));

ALTER TABLE H_USUARIOS ADD CONSTRAINT ND_TELEFONO UNIQUE (TELEFONO);

ALTER TABLE H_USUARIOS ADD CONSTRAINT FK_USER_ROL FOREIGN KEY (ROL) REFERENCES H_ROLES (ID);	

-- Tabla tipo habitaciones

CREATE TABLE H_TIPO_HABITACIONES (ID NUMBER, NOMBRE VARCHAR2 (255 BYTE) NOT NULL, DESCRIPCION VARCHAR2 (255 BYTE) NOT NULL, CONSTRAINT H_TIPO_HABITACIONES_PK PRIMARY KEY (ID));

-- Tabla habitaciones

CREATE TABLE H_HABITACIONES (ID NUMBER, HAB_NUM NUMBER, ID_HOTEL NUMBER, ID_TIPO NUMBER, RESERVADA NUMBER NOT NULL, PRECIONOCHE NUMBER NOT NULL, CONSTRAINT H_HABITACIONES_PK PRIMARY KEY (ID));

ALTER TABLE H_HABITACIONES ADD CONSTRAINT CK_RESERVADA CHECK (RESERVADA IN (0,1));

ALTER TABLE H_HABITACIONES ADD CONSTRAINT FK_HAB_TIPO_HABITACIONES FOREIGN KEY (ID_TIPO) REFERENCES H_TIPO_HABITACIONES (ID) ENABLE;

ALTER TABLE H_HABITACIONES ADD CONSTRAINT FK_HAB_HOTEL FOREIGN KEY (ID_HOTEL) REFERENCES H_HOTELES (ID) ENABLE;

-- Tabla ocupan

CREATE TABLE H_OCUPAN (ID_HABITACION NUMBER, NUMDOCUMENTO NUMBER, CONSTRAINT H_OCUPAN_PK PRIMARY KEY (ID_HABITACION));

ALTER TABLE H_OCUPAN ADD CONSTRAINT FK_O_HABITACIONES FOREIGN KEY (ID_HABITACION) REFERENCES H_HABITACIONES (ID) ENABLE;

ALTER TABLE H_OCUPAN ADD CONSTRAINT FK_O_CLIENTES FOREIGN KEY (NUMDOCUMENTO) REFERENCES H_USUARIOS (NUMDOCUMENTO) ENABLE;

-- Tabla ofrecen

CREATE TABLE H_OFRECEN (ID_SERVICIO NUMBER, ID_PRODUCTO NUMBER, CONSTRAINT H_OFRECEN_PK PRIMARY KEY (ID_SERVICIO));

ALTER TABLE H_OFRECEN ADD CONSTRAINT FK_O_SERVICIOS FOREIGN KEY (ID_SERVICIO) REFERENCES H_SERVICIOS_HOTEL (ID) ENABLE;

ALTER TABLE H_OFRECEN ADD CONSTRAINT FK_O_PRODUCTOS FOREIGN KEY (ID_PRODUCTO) REFERENCES H_PRODUCTOS_INSTALACIONES (ID_ITEM) ENABLE;

COMMIT;