    
-- Eliminar todas las tablas de la base de datos
DROP TABLE "H_HOTELES" CASCADE CONSTRAINTS;
DROP TABLE "H_ACOMPANANTES" CASCADE CONSTRAINTS;
DROP TABLE "H_PLANES" CASCADE CONSTRAINTS;
DROP TABLE "H_RESERVACIONES_HOTEL" CASCADE CONSTRAINTS;
DROP TABLE "H_SALONPRESTAMO" CASCADE CONSTRAINTS;
DROP TABLE "H_SERVICIOS_HOTEL" CASCADE CONSTRAINTS;
DROP TABLE "H_CUENTAS" CASCADE CONSTRAINTS;
DROP TABLE "H_CLIENTESRESERVAS" CASCADE CONSTRAINTS;
DROP TABLE "H_USUARIOS" CASCADE CONSTRAINTS;
DROP TABLE "H_GIMNASIOS" CASCADE CONSTRAINTS;
DROP TABLE "H_TIENENMAQUINAS" CASCADE CONSTRAINTS;
DROP TABLE "H_TIPO_HABITACIONES" CASCADE CONSTRAINTS;
DROP TABLE "H_HABITACIONES" CASCADE CONSTRAINTS;
DROP TABLE "H_OCUPAN" CASCADE CONSTRAINTS;
DROP TABLE "H_PRODUCTOS_INSTALACIONES" CASCADE CONSTRAINTS;
DROP TABLE "H_OFRECEN" CASCADE CONSTRAINTS;
DROP TABLE "H_PISCINAS" CASCADE CONSTRAINTS;
DROP TABLE "H_RESTAURANTES_BAR" CASCADE CONSTRAINTS;
DROP TABLE "H_SPAS" CASCADE CONSTRAINTS;
DROP TABLE "H_SUPERMERCADOS_TIENDAS" CASCADE CONSTRAINTS;
DROP TABLE "H_ROLES" CASCADE CONSTRAINTS;
DROP TABLE "H_INTERNET" CASCADE CONSTRAINTS;
DROP TABLE "H_PRESTAMO" CASCADE CONSTRAINTS;
DROP TABLE "H_LAVANDERIA" CASCADE CONSTRAINTS;
DROP SEQUENCE HOTELES_SEQUENCE;
COMMIT;

