-- POBLAR HOTELES
INSERT INTO H_HOTELES (ID, NOMBRE, UBICACION, CATEGORIA, TELEFONO) VALUES (0, 'Hotel Oasis', 'Calle falsa #123', 'Cinco estrellas', 11111);

SELECT * FROM H_HOTELES;
DELETE  FROM H_HOTELES ;

--POBLAR TIPO HABITACIONES
INSERT INTO H_TIPO_HABITACIONES (ID, NOMBRE, DESCRIPCION) VALUES (0, 'Sencilla', 'Cama sencilla, televisor, escritorio y baño privado');
INSERT INTO H_TIPO_HABITACIONES (ID, NOMBRE, DESCRIPCION) VALUES (1, 'Doble', 'Cama doble, televisor, escritorio, minibar, clóset y baño privado');
INSERT INTO H_TIPO_HABITACIONES (ID, NOMBRE, DESCRIPCION) VALUES (2, 'Suite', 'Cama king, televisor 52'', sofá, escritorio, sala, jacuzzi, tina en baño privado, minibar, cocina y balcón');
SELECT * FROM H_TIPO_HABITACIONES;
DELETE FROM H_TIPO_HABITACIONES;

--POBLAR HABITACIONES
    --HOTEL 0
INSERT INTO H_HABITACIONES(ID,HAB_NUM,ID_HOTEL,ID_TIPO,RESERVADA,PRECIONOCHE) VALUES (0,101,0,0,0,50000);
INSERT INTO H_HABITACIONES(ID,HAB_NUM,ID_HOTEL,ID_TIPO,RESERVADA,PRECIONOCHE) VALUES (1,102,0,0,0,50000);
INSERT INTO H_HABITACIONES(ID,HAB_NUM,ID_HOTEL,ID_TIPO,RESERVADA,PRECIONOCHE) VALUES (2,103,0,1,0,70000);
INSERT INTO H_HABITACIONES(ID,HAB_NUM,ID_HOTEL,ID_TIPO,RESERVADA,PRECIONOCHE) VALUES (3,104,0,1,0,70000);
INSERT INTO H_HABITACIONES(ID,HAB_NUM,ID_HOTEL,ID_TIPO,RESERVADA,PRECIONOCHE) VALUES (4,105,0,2,0,200000); 

--SERVICIOS
    --GYM
        --HOTEL 0
INSERT INTO H_GIMNASIOS (ID, NOMBRE, PRECIO, PRECIOADICIONAL) VALUES (0, 'Gimnasio principal', 0, 0);
INSERT INTO H_TIENENMAQUINAS(ID_GIMNASIO, NOMBRE_MAQUINA) VALUES (0, 'CAMINADORA');
INSERT INTO H_TIENENMAQUINAS(ID_GIMNASIO, NOMBRE_MAQUINA) VALUES (0, 'ELIPTICA');
INSERT INTO H_SERVICIOS_HOTEL (ID, IDHOTEL, ID_SPA, ID_SUPERMERCADOTIENDA, ID_PISCINA, ID_RESTAURANTEBAR, ID_GIMNASIO, ID_PRESTAMO, ID_PRESTAMOSALON, ID_INTERNET, ID_LAV_PLAN_EMB) VALUES (0, 0, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL);
    --SALONES
-- Salon reuniones
INSERT INTO H_SALONPRESTAMO (ID, TIPO, ID_HOTEL, CAPACIDAD, COSTO) VALUES (0, 'Salon reunion', 0, 12, 30000);
INSERT INTO H_SERVICIOS_HOTEL (ID, IDHOTEL, ID_SPA, ID_SUPERMERCADOTIENDA, ID_PISCINA, ID_RESTAURANTEBAR, ID_GIMNASIO, ID_PRESTAMO, ID_PRESTAMOSALON, ID_INTERNET, ID_LAV_PLAN_EMB) VALUES (1,0 ,NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL);
-- Salon conferencias
INSERT INTO H_SALONPRESTAMO (ID, TIPO, ID_HOTEL, CAPACIDAD, COSTO) VALUES (1, 'Salon conferencia', 0, 100, 75000);
INSERT INTO H_SERVICIOS_HOTEL (ID, IDHOTEL, ID_SPA, ID_SUPERMERCADOTIENDA, ID_PISCINA, ID_RESTAURANTEBAR, ID_GIMNASIO, ID_PRESTAMO, ID_PRESTAMOSALON, ID_INTERNET, ID_LAV_PLAN_EMB) VALUES (2, 0, NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL);
    --PISCINA  
INSERT INTO H_PISCINAS (ID, NOMBRE, PRECIO, PAGO_ADICIONAL, CAPACIDAD, HORARIO_INICIAL, HORARIO_FINAL) VALUES (0, 'Piscina principal', 0, 0, 50, '09:00', '22:00');
INSERT INTO H_SERVICIOS_HOTEL (ID, IDHOTEL, ID_SPA, ID_SUPERMERCADOTIENDA, ID_PISCINA, ID_RESTAURANTEBAR, ID_GIMNASIO, ID_PRESTAMO, ID_PRESTAMOSALON, ID_INTERNET, ID_LAV_PLAN_EMB) VALUES (3, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL);
     --RESTAURANTE
INSERT INTO H_RESTAURANTES_BAR (ID, TIPO, NOMBRE,CAPACIDAD, TEMATICA) VALUES (0,'Restaurante', 'Al wok', 50, 'Restaurante oriental');
INSERT INTO H_PRODUCTOS_INSTALACIONES (ID_ITEM, NOMBRE, PRECIO) VALUES (0, 'Vegetales con carne al wok', 15000);
INSERT INTO H_PRODUCTOS_INSTALACIONES (ID_ITEM, NOMBRE, PRECIO) VALUES (1, 'Limonada de coco', 7000);
INSERT INTO H_PRODUCTOS_INSTALACIONES (ID_ITEM, NOMBRE, PRECIO) VALUES (2, 'Postre a base de mochi', 10000);
INSERT INTO H_SERVICIOS_HOTEL (ID, IDHOTEL, ID_SPA, ID_SUPERMERCADOTIENDA, ID_PISCINA, ID_RESTAURANTEBAR, ID_GIMNASIO, ID_PRESTAMO, ID_PRESTAMOSALON, ID_INTERNET, ID_LAV_PLAN_EMB) VALUES (4, 0, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL);
INSERT INTO H_OFRECEN (ID_SERVICIO, ID_PRODUCTO) VALUES (4, 0);
INSERT INTO H_OFRECEN (ID_SERVICIO, ID_PRODUCTO) VALUES (4, 1);
INSERT INTO H_OFRECEN (ID_SERVICIO, ID_PRODUCTO) VALUES (4, 2);
    --BAR
INSERT INTO H_RESTAURANTES_BAR (ID,TIPO, NOMBRE, CAPACIDAD, TEMATICA) VALUES (1,'Bar', 'Bar oculto', 100, 'Bar de jazz');
INSERT INTO H_PRODUCTOS_INSTALACIONES (ID_ITEM, NOMBRE, PRECIO) VALUES (3, 'Cerveza nacional', 5000);
INSERT INTO H_PRODUCTOS_INSTALACIONES (ID_ITEM, NOMBRE, PRECIO) VALUES (4, 'Cerveza internacional', 7000);
INSERT INTO H_PRODUCTOS_INSTALACIONES (ID_ITEM, NOMBRE, PRECIO) VALUES (5, 'Dry martini', 15000);
INSERT INTO H_SERVICIOS_HOTEL (ID, IDHOTEL, ID_SPA, ID_SUPERMERCADOTIENDA, ID_PISCINA, ID_RESTAURANTEBAR, ID_GIMNASIO, ID_PRESTAMO, ID_PRESTAMOSALON, ID_INTERNET, ID_LAV_PLAN_EMB) VALUES (5, 0, NULL, NULL, NULL, 1, NULL, NULL, NULL, NULL, NULL);
INSERT INTO H_OFRECEN (ID_SERVICIO, ID_PRODUCTO) VALUES (5, 4);
INSERT INTO H_OFRECEN (ID_SERVICIO, ID_PRODUCTO) VALUES (5, 5);
INSERT INTO H_OFRECEN (ID_SERVICIO, ID_PRODUCTO) VALUES (5, 6);

--POBLAR PLANES DE PAGO
INSERT INTO H_PLANES(ID,NOMBRE,DESCUENTO,NUMNOCHES)VALUES(0,'Plan Convencion',35,7);
INSERT INTO H_PLANES(ID,NOMBRE,DESCUENTO,NUMNOCHES)VALUES(1,'Plan Larga Duracion',25,7);
INSERT INTO H_PLANES(ID,NOMBRE,DESCUENTO,NUMNOCHES)VALUES(2,'Plan Incluido',30,7);
INSERT INTO H_PLANES(ID,NOMBRE,DESCUENTO,NUMNOCHES)VALUES(3,'Plan Otra Promo',15,7);
INSERT INTO H_PLANES(ID,NOMBRE,DESCUENTO,NUMNOCHES)VALUES(4,'Mantenimiento',15,7);
